# Generated by Django 3.2 on 2023-09-21 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Product name')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('images', models.ImageField(upload_to='photos/products', verbose_name='images')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available ?')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'ordering': ('-created_date',),
            },
        ),
    ]
