# Generated by Django 3.2 on 2023-09-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_slug_product_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
